import Link from 'next/link';
import { ArrowLeft, ImageIcon, Save, ShieldCheck, Video } from 'lucide-react';

import { requireAdminPermission } from '@/features/admin/auth/adminPermissions';
import { updateStorefrontHero } from '@/features/admin/hero/actions';
import { prisma } from '@/lib/prisma';

const fallbackVideo = 'https://assets.mixkit.co/videos/preview/mixkit-friends-having-dinner-at-a-restaurant-4340-large.mp4';
const inputClass = 'min-h-11 w-full rounded-2xl border border-border/70 bg-background/75 px-3 py-2 text-sm outline-none focus:border-primary focus:ring-2 focus:ring-primary/10';

export default async function AdminHeroPage() {
  const access = await requireAdminPermission('system:manage');
  const hero = await prisma.storefrontHero.findUnique({ where: { workspaceId: access.membership.workspaceId } }).catch(() => null);
  const mediaType = hero?.mediaType === 'IMAGE' ? 'IMAGE' : 'VIDEO';
  const mediaUrl = hero?.mediaUrl || fallbackVideo;

  return <main className="min-h-dvh bg-[radial-gradient(circle_at_top_right,hsl(var(--primary)/.1),transparent_35%)] px-3 py-5 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl space-y-5">
    <header className="rounded-[2rem] border border-border/60 bg-card/80 p-5 shadow-xl sm:p-7"><Link href="/admin" className="inline-flex items-center gap-2 text-xs text-muted-foreground"><ArrowLeft className="size-4" /> Admin attention center</Link><div className="mt-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[10px] font-black uppercase tracking-[.2em] text-primary">Storefront studio</p><h1 className="mt-2 text-3xl font-black sm:text-5xl">Homepage hero</h1><p className="mt-2 max-w-2xl text-sm text-muted-foreground">Control the cinematic media, onboarding message, and entry actions shown above the storefront.</p></div><span className="inline-flex w-fit items-center gap-2 rounded-full bg-emerald-500/10 px-3 py-2 text-[10px] font-bold text-emerald-600"><ShieldCheck className="size-4" /> Super Admin only</span></div></header>

    <form action={updateStorefrontHero} className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_minmax(25rem,.8fr)]">
      <div className="space-y-5">
        <section className="rounded-[2rem] border border-border/60 bg-card/75 p-5 shadow-lg sm:p-6"><h2 className="font-black">Media treatment</h2><p className="mt-1 text-xs text-muted-foreground">Use a direct hosted video or image URL. Poster artwork is displayed while video loads.</p><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="Media type"><select name="mediaType" defaultValue={mediaType} className={inputClass}><option value="VIDEO">Video</option><option value="IMAGE">Image</option></select></Field><Field label="Background media URL"><input name="mediaUrl" type="url" defaultValue={mediaUrl} className={inputClass} /></Field></div><Field label="Video poster / fallback image URL"><input name="posterUrl" type="url" defaultValue={hero?.posterUrl ?? ''} className={inputClass} /></Field><div className="mt-4 grid gap-3 sm:grid-cols-2"><Toggle name="enabled" label="Hero enabled" defaultChecked={hero?.enabled ?? true} /><Toggle name="autoplay" label="Autoplay muted video" defaultChecked={hero?.autoplay ?? true} /></div></section>
        <section className="rounded-[2rem] border border-border/60 bg-card/75 p-5 shadow-lg sm:p-6"><h2 className="font-black">Onboarding story</h2><div className="mt-5 space-y-4"><Field label="Eyebrow"><input name="eyebrow" defaultValue={hero?.eyebrow ?? 'Your personal shopping experience'} className={inputClass} /></Field><Field label="Hero title"><input name="title" required defaultValue={hero?.title ?? 'Every beautiful moment starts here.'} className={inputClass} /></Field><Field label="Summary"><textarea name="summary" rows={4} defaultValue={hero?.summary ?? 'Build shopping lists like playlists, discover elegant experiences shaped around your taste, and move every pick from inspiration to delivery in one personal hub.'} className={inputClass} /></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Primary button label"><input name="primaryLabel" defaultValue={hero?.primaryLabel ?? 'Create your experience'} className={inputClass} /></Field><Field label="Primary button link"><input name="primaryHref" defaultValue={hero?.primaryHref ?? '/sign-up'} className={inputClass} /></Field><Field label="Secondary button label"><input name="secondaryLabel" defaultValue={hero?.secondaryLabel ?? 'Sign in'} className={inputClass} /></Field><Field label="Secondary button link"><input name="secondaryHref" defaultValue={hero?.secondaryHref ?? '/sign-in'} className={inputClass} /></Field></div></div></section>
      </div>
      <aside className="space-y-4 xl:sticky xl:top-24 xl:self-start"><section className="overflow-hidden rounded-[2rem] border border-border/60 bg-[#03070d] text-white shadow-2xl"><div className="relative aspect-[4/3]">{mediaType === 'VIDEO' ? <video muted loop autoPlay playsInline poster={hero?.posterUrl ?? undefined} className="absolute inset-0 size-full object-cover"><source src={mediaUrl} /></video> : <div className="absolute inset-0 bg-cover bg-center" style={{ backgroundImage: `url(${mediaUrl})` }} />}<div className="absolute inset-0 bg-gradient-to-r from-black/90 via-black/50 to-transparent" /><div className="absolute inset-0 flex items-end p-6"><div><p className="text-[9px] font-bold uppercase tracking-[.18em] text-amber-300">{hero?.eyebrow ?? 'Your personal shopping experience'}</p><h2 className="mt-2 text-2xl font-black">{hero?.title ?? 'Every beautiful moment starts here.'}</h2></div></div></div><div className="flex items-center gap-2 border-t border-white/10 p-4 text-[10px] text-white/60">{mediaType === 'VIDEO' ? <Video className="size-4" /> : <ImageIcon className="size-4" />} Current saved preview</div></section><button className="inline-flex h-12 w-full items-center justify-center gap-2 rounded-full bg-foreground text-sm font-bold text-background shadow-lg"><Save className="size-4" /> Publish homepage hero</button></aside>
    </form>
  </div></main>;
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="mt-4 block"><span className="mb-2 block text-[10px] font-bold uppercase tracking-[.14em] text-muted-foreground">{label}</span>{children}</label>; }
function Toggle({ name, label, defaultChecked }: { name: string; label: string; defaultChecked: boolean }) { return <label className="flex items-center gap-3 rounded-2xl border border-border/60 bg-background/55 p-3 text-xs font-bold"><input type="checkbox" name={name} defaultChecked={defaultChecked} />{label}</label>; }
