import Link from 'next/link';
import { ArrowLeft, ArrowRight, LockKeyhole, ShieldCheck, UsersRound } from 'lucide-react';

import { requireAdminPermission } from '@/features/admin/auth/adminPermissions';
import { prisma } from '@/lib/prisma';

export default async function AdminAccountsPage() {
  const access = await requireAdminPermission('system:manage');
  const actor = await prisma.user.findUniqueOrThrow({ where: { id: access.session.user.id }, select: { isGhostDeveloper: true } });
  const users = await prisma.user.findMany({ where: actor.isGhostDeveloper ? {} : { isGhostDeveloper: false }, select: { id: true, name: true, email: true, tier: true, accountState: true, lockedUntil: true, emailVerified: true, workspaceMemberships: { where: { active: true }, select: { role: true } } }, orderBy: { createdAt: 'desc' }, take: 100 });
  return <main className="min-h-dvh px-3 py-5 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl space-y-5"><header className="rounded-[2rem] border border-border/60 bg-card/80 p-5 shadow-xl sm:p-7"><Link href="/admin" className="inline-flex items-center gap-2 text-xs text-muted-foreground"><ArrowLeft className="size-4" /> Admin attention center</Link><div className="mt-6 flex items-end justify-between"><div><p className="text-[10px] font-black uppercase tracking-[.2em] text-primary">Super Admin authority</p><h1 className="mt-2 text-3xl font-black sm:text-5xl">Account control</h1><p className="mt-2 text-sm text-muted-foreground">Manage customer and administrator identity, verification, access state, and credentials.</p></div><span className="hidden rounded-full bg-primary/10 px-3 py-2 text-xs font-bold text-primary sm:block">{users.length} visible accounts</span></div></header><section className="rounded-[2rem] border border-border/60 bg-card/70 p-3 shadow-lg sm:p-5"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{users.map(user => { const role = user.workspaceMemberships.find(item => item.role !== 'MEMBER')?.role; return <Link key={user.id} href={`/admin/accounts/${user.id}`} className="group rounded-3xl border border-border/60 bg-background/65 p-4 transition hover:-translate-y-0.5 hover:shadow-lg"><div className="flex items-start justify-between"><span className="grid size-11 place-items-center rounded-2xl bg-muted text-sm font-black">{user.name.charAt(0)}</span><State state={user.accountState} /></div><h2 className="mt-4 truncate text-sm font-black">{user.name}</h2><p className="mt-1 truncate text-[10px] text-muted-foreground">{user.email}</p><div className="mt-4 flex items-center gap-2"><span className="rounded-full bg-muted px-2 py-1 text-[8px] font-bold">{role?.replaceAll('_', ' ') ?? user.tier ?? 'MEMBER'}</span>{user.emailVerified ? <ShieldCheck className="size-3.5 text-emerald-500" /> : null}<ArrowRight className="ml-auto size-4 text-muted-foreground transition group-hover:translate-x-1" /></div>{user.lockedUntil ? <p className="mt-3 flex items-center gap-1 text-[9px] text-amber-600"><LockKeyhole className="size-3" /> Until {user.lockedUntil.toLocaleString('en-NG')}</p> : null}</Link>; })}</div>{!users.length ? <div className="grid min-h-52 place-items-center text-center"><UsersRound className="size-7 text-muted-foreground" /></div> : null}</section></div></main>;
}
function State({ state }: { state: string }) { const style = state === 'ACTIVE' ? 'bg-emerald-500/10 text-emerald-600' : state === 'LOCKED' ? 'bg-amber-500/10 text-amber-600' : 'bg-rose-500/10 text-rose-600'; return <span className={`rounded-full px-2 py-1 text-[8px] font-black ${style}`}>{state}</span>; }
