import { CheckCircle2, Clock3, ShieldCheck, XCircle } from 'lucide-react';

import { reviewAdminApproval } from '@/features/admin/approvals/actions';
import { getAdminAccess } from '@/features/admin/auth/adminPermissions';
import { AdminMetric, AdminPage, AdminPageHeader } from '@/features/admin/components';
import { prisma } from '@/lib/prisma';

export default async function AdminApprovalsPage(){const access=await getAdminAccess();if(!access.permissions.has('approval:view'))throw new Error('Approval access is required.');const requests=await prisma.adminApprovalRequest.findMany({where:{workspaceId:access.membership.workspaceId},include:{requestedBy:{select:{name:true,email:true}},reviewedBy:{select:{name:true}}},orderBy:{createdAt:'desc'},take:150});const pending=requests.filter(r=>r.status==='PENDING').length;const approved=requests.filter(r=>['APPROVED','EXECUTED'].includes(r.status)).length;const rejected=requests.filter(r=>r.status==='REJECTED').length;return <AdminPage><div className="mx-auto max-w-[96rem] space-y-5"><AdminPageHeader eyebrow="Moderation and governance" title="Approval Studio" description="Review controlled product, promotion, collection, vendor, campaign, delivery and destructive operations from one immutable queue."/><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><AdminMetric icon={Clock3} label="Pending" value={pending}/><AdminMetric icon={CheckCircle2} label="Approved or executed" value={approved}/><AdminMetric icon={XCircle} label="Rejected" value={rejected}/><AdminMetric icon={ShieldCheck} label="Total requests" value={requests.length}/></section><section className="grid gap-4 lg:grid-cols-2">{requests.map(request=><article key={request.id} className="rounded-[2rem] border border-border/60 bg-card/75 p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><p className="text-[9px] font-bold uppercase tracking-[.14em] text-primary">{request.targetType} · {request.action.replaceAll('_',' ')}</p><h2 className="mt-2 text-sm font-black">{request.reason}</h2><p className="mt-1 text-[10px] text-muted-foreground">Requested by {request.requestedBy.name} · {request.createdAt.toLocaleString('en-NG')}</p></div><span className={request.status==='PENDING'?'rounded-full bg-amber-500/10 px-2 py-1 text-[8px] font-bold text-amber-600':request.status==='REJECTED'?'rounded-full bg-rose-500/10 px-2 py-1 text-[8px] font-bold text-rose-600':'rounded-full bg-emerald-500/10 px-2 py-1 text-[8px] font-bold text-emerald-600'}>{request.status}</span></div>{request.reviewNote?<p className="mt-4 rounded-2xl bg-muted/50 p-3 text-xs text-muted-foreground">{request.reviewNote}</p>:null}{request.status==='PENDING'&&access.permissions.has('approval:review')?<div className="mt-4 grid gap-2 sm:grid-cols-2"><Decision id={request.id} decision="APPROVED"/><Decision id={request.id} decision="REJECTED"/></div>:null}{request.reviewedBy?<p className="mt-4 text-[9px] text-muted-foreground">Reviewed by {request.reviewedBy.name}</p>:null}</article>)}</section></div></AdminPage>}
function Decision({id,decision}:{id:string;decision:'APPROVED'|'REJECTED'}){return <form action={reviewAdminApproval} className="rounded-2xl border border-border/60 p-3"><input type="hidden" name="id" value={id}/><input type="hidden" name="decision" value={decision}/><textarea name="reviewNote" rows={2} placeholder={`${decision==='APPROVED'?'Approval':'Rejection'} note`} className="w-full resize-none rounded-xl border border-border/60 bg-background p-2 text-[10px] outline-none"/><button className={decision==='APPROVED'?'mt-2 h-9 w-full rounded-full bg-foreground text-[9px] font-bold text-background':'mt-2 h-9 w-full rounded-full border border-border text-[9px] font-bold'}>{decision==='APPROVED'?'Approve and execute':'Reject request'}</button></form>}
