import type { Metadata } from 'next';
import { Geist, Geist_Mono, Inter } from 'next/font/google';
import './globals.css';
import NavbarComponent from '@/components/Navbar';
import { cn } from '@/lib/utils';
import FooterComponent from '@/components/FooterComponent';
import ThemeProvider from '@/components/providers/ThemeProvider';
import { SidebarProvider } from '@/components/ui/sidebar';
import { AppSidebar } from '@/components/providers/AppSideBar';
import { Suspense } from 'react';

// type BrandType = {
//   brandName: string;
//   brandSlug: string;
// };

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={cn(
        'h-full',
        'antialiased',
        geistSans.variable,
        geistMono.variable,
        'font-sans',
        inter.variable
      )}>
      <body>
        <ThemeProvider attribute="class" defaultTheme="light" enableSystem disableTransitionOnChange>
          <SidebarProvider defaultOpen={false}>
            <AppSidebar />

            <main className="flex flex-col w-full min-h-screen">
              {/* SINGLE UNIFIED TOP BAR */}
              <div className="sticky top-0 z-50">
                <Suspense fallback={null}>
                  <NavbarComponent brandName="AJ" brandSlug="Store" />
                </Suspense>
              </div>

              <div className="w-full flex flex-col flex-1">{children}</div>

              <FooterComponent brandName="AJ" brandSlug="Store" />
            </main>
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
