import type { Metadata } from 'next';
import { Geist, Geist_Mono, Inter } from 'next/font/google';
import './globals.css';
import NavbarComponent from '@/components/Navbar';
import { cn } from '@/lib/utils';
import FooterComponent from '@/components/FooterComponent';
import { SidebarProvider, SidebarTrigger } from '@/components/ui/sidebar';
import { AppSidebar } from '@/components/AppSidebar';
import ThemeProvider from '@/components/providers/ThemeProvider';

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={cn(
        'h-full',
        'antialiased',
        geistSans.variable,
        geistMono.variable,
        'font-sans',
        inter.variable
      )}>
      <body>
        <ThemeProvider attribute="class" defaultTheme="light" enableSystem disableTransitionOnChange>
          {/* 
          <SidebarProvider className="">
            <AppSidebar />
            <SidebarTrigger className="text-rose-500 top-5  w-10 h-10 rounded-full bg-primary-foreground hidden md:sticky z-10" /> */}
          <main className="flex flex-col w-full h-full">
            <NavbarComponent />
            <div className="w-full h-full flex flex-col m-auto grow px-6">{children}</div>
            <FooterComponent />
          </main>
          {/* </SidebarProvider>*/}
        </ThemeProvider>
      </body>
    </html>
  );
}
