import Link from 'next/link';
import { ArrowLeft, Barcode, MapPin, PackageCheck, Truck } from 'lucide-react';

import { getAdminAccess } from '@/features/admin/auth/adminPermissions';
import { prisma } from '@/lib/prisma';

export default async function AdminDeliveriesPage() {
  const access = await getAdminAccess();
  const deliveries = await prisma.delivery.findMany({ where: { workspaceId: access.membership.workspaceId }, include: { order: { select: { orderNumber: true, user: { select: { name: true } } } }, dispatcher: { select: { name: true } }, _count: { select: { events: true } } }, orderBy: { updatedAt: 'desc' }, take: 50 });
  return <main className="min-h-dvh px-3 py-5 sm:px-6 lg:px-8"><div className="mx-auto max-w-6xl space-y-5"><header className="rounded-[2rem] border border-border/60 bg-card/80 p-5 shadow-xl sm:p-7"><Link href="/admin" className="inline-flex items-center gap-2 text-xs text-muted-foreground"><ArrowLeft className="size-4" /> Attention center</Link><p className="mt-6 text-[10px] font-bold uppercase tracking-[0.2em] text-primary/70">Live operations</p><h1 className="mt-2 text-3xl font-black sm:text-4xl">Delivery control</h1><p className="mt-2 text-sm text-muted-foreground">AJ Delivery, personal courier barcode access, and store pickup activity.</p></header><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{deliveries.map(delivery => <article key={delivery.id} className="rounded-3xl border border-border/60 bg-card/70 p-5 shadow-sm"><div className="flex items-center justify-between"><div className="grid size-11 place-items-center rounded-2xl bg-primary/10 text-primary"><Truck className="size-5" /></div><span className="rounded-full bg-muted px-2 py-1 text-[8px] font-bold">{delivery.status.replaceAll('_', ' ')}</span></div><h2 className="mt-4 text-sm font-bold">{delivery.order.orderNumber}</h2><p className="mt-1 text-[10px] text-muted-foreground">{delivery.order.user.name} · {delivery.method.replaceAll('_', ' ')}</p><div className="mt-4 space-y-2 rounded-2xl bg-muted/40 p-3 text-[10px]"><p className="flex items-center gap-2"><Barcode className="size-3.5" /> {delivery.trackingCode}</p><p className="flex items-center gap-2"><MapPin className="size-3.5" /> {delivery.trackingEnabled ? 'Live tracking enabled' : 'Tracking waiting for scan'}</p><p className="flex items-center gap-2"><PackageCheck className="size-3.5" /> {delivery._count.events} tracking events</p></div><p className="mt-4 text-[9px] text-muted-foreground">Dispatcher: {delivery.dispatcher?.name ?? delivery.dispatcherName ?? 'Not assigned'}</p></article>)}</section>{!deliveries.length ? <section className="grid min-h-64 place-items-center rounded-[2rem] border border-dashed border-border/70 bg-card/50 text-center"><div><Truck className="mx-auto size-7 text-muted-foreground" /><p className="mt-3 text-sm font-bold">No deliveries created yet</p><p className="mt-1 text-xs text-muted-foreground">Delivery records will appear when checkout fulfillment is connected.</p></div></section> : null}</div></main>;
}
