import Link from 'next/link';
import { ArrowLeft, KeyRound, Save, ShieldCheck, UserRound } from 'lucide-react';

import { getAdminAccess } from '@/features/admin/auth/adminPermissions';
import { updateOwnAdminAccount } from '@/features/admin/accounts/actions';
import { prisma } from '@/lib/prisma';

const field = 'h-11 w-full rounded-2xl border border-border/70 bg-background px-3 text-sm outline-none focus:border-primary';

export default async function AdminAccountPage() {
  const access = await getAdminAccess();
  const user = await prisma.user.findUniqueOrThrow({ where: { id: access.session.user.id }, select: { name: true, email: true, isGhostDeveloper: true } });
  return <main className="min-h-dvh px-3 py-5 sm:px-6 lg:px-8"><div className="mx-auto max-w-4xl space-y-5"><header className="rounded-[2rem] border border-border/60 bg-card/80 p-5 shadow-xl sm:p-7"><Link href="/admin" className="inline-flex items-center gap-2 text-xs text-muted-foreground"><ArrowLeft className="size-4" /> Admin attention center</Link><div className="mt-6 flex items-end justify-between gap-4"><div><p className="text-[10px] font-black uppercase tracking-[.2em] text-primary">Private administrator profile</p><h1 className="mt-2 text-3xl font-black sm:text-4xl">Your account</h1><p className="mt-2 text-sm text-muted-foreground">Update your own identity and rotate your password securely.</p></div><ShieldCheck className="size-8 text-emerald-500" /></div></header><form action={updateOwnAdminAccount} className="grid gap-5 md:grid-cols-2"><section className="rounded-[2rem] border border-border/60 bg-card/75 p-5 shadow-lg sm:p-6"><div className="flex items-center gap-3"><UserRound className="size-5 text-primary" /><h2 className="font-black">Identity</h2></div><label className="mt-5 block text-xs font-bold">Full name<input name="name" required defaultValue={user.name} className={`${field} mt-2`} /></label><label className="mt-4 block text-xs font-bold">Email address<input name="email" type="email" required defaultValue={user.email} className={`${field} mt-2`} /></label>{user.isGhostDeveloper ? <p className="mt-4 rounded-2xl bg-primary/10 p-3 text-[10px] font-semibold text-primary">Protected developer identity. This profile is hidden from every other administrator.</p> : null}</section><section className="rounded-[2rem] border border-border/60 bg-card/75 p-5 shadow-lg sm:p-6"><div className="flex items-center gap-3"><KeyRound className="size-5 text-primary" /><h2 className="font-black">Security</h2></div><label className="mt-5 block text-xs font-bold">Current password<input name="currentPassword" type="password" required autoComplete="current-password" className={`${field} mt-2`} /></label><label className="mt-4 block text-xs font-bold">New password <span className="font-normal text-muted-foreground">(optional)</span><input name="newPassword" type="password" minLength={8} autoComplete="new-password" className={`${field} mt-2`} /></label><button className="mt-6 inline-flex h-11 w-full items-center justify-center gap-2 rounded-full bg-foreground text-xs font-bold text-background"><Save className="size-4" /> Save account securely</button></section></form></div></main>;
}
