import Link from 'next/link';
import { ArrowLeft, KeyRound, Save, ShieldAlert, UserCog } from 'lucide-react';
import { notFound } from 'next/navigation';

import { requireAdminPermission } from '@/features/admin/auth/adminPermissions';
import { updateManagedAccount } from '@/features/admin/accounts/actions';
import { prisma } from '@/lib/prisma';

const field = 'h-11 w-full rounded-2xl border border-border/70 bg-background px-3 text-sm outline-none focus:border-primary';
export default async function ManagedAccountPage({ params }: { params: Promise<{ id: string }> }) {
  const access = await requireAdminPermission('system:manage'); const { id } = await params;
  const [actor, user] = await Promise.all([prisma.user.findUnique({ where: { id: access.session.user.id }, select: { isGhostDeveloper: true } }), prisma.user.findUnique({ where: { id }, select: { id: true, name: true, email: true, tier: true, emailVerified: true, accountState: true, lockedUntil: true, restrictionReason: true, isGhostDeveloper: true } })]);
  if (!user || (user.isGhostDeveloper && !actor?.isGhostDeveloper)) notFound();
  return <main className="min-h-dvh px-3 py-5 sm:px-6 lg:px-8"><div className="mx-auto max-w-5xl space-y-5"><header className="rounded-[2rem] border border-border/60 bg-card/80 p-5 shadow-xl sm:p-7"><Link href="/admin/accounts" className="inline-flex items-center gap-2 text-xs text-muted-foreground"><ArrowLeft className="size-4" /> Account control</Link><p className="mt-6 text-[10px] font-black uppercase tracking-[.2em] text-primary">Managed identity</p><h1 className="mt-2 text-3xl font-black sm:text-4xl">{user.name}</h1><p className="mt-2 text-sm text-muted-foreground">Changes are audited. Restrictions revoke all active sessions immediately.</p></header><form action={updateManagedAccount} className="grid gap-5 lg:grid-cols-[1fr_22rem]"><input type="hidden" name="userId" value={user.id} /><section className="rounded-[2rem] border border-border/60 bg-card/75 p-5 shadow-lg sm:p-6"><div className="flex items-center gap-3"><UserCog className="size-5 text-primary" /><h2 className="font-black">Profile and commerce identity</h2></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="Full name"><input name="name" required defaultValue={user.name} className={field} /></Field><Field label="Email"><input name="email" type="email" required defaultValue={user.email} className={field} /></Field><Field label="Customer tier"><input name="tier" defaultValue={user.tier ?? 'member'} className={field} /></Field><label className="flex items-center gap-3 self-end rounded-2xl border border-border/60 p-3 text-xs font-bold"><input name="emailVerified" type="checkbox" defaultChecked={user.emailVerified} /> Email verified</label></div><div className="mt-6 flex items-center gap-3"><KeyRound className="size-5 text-primary" /><h2 className="font-black">Credential reset</h2></div><Field label="Replacement password (optional)"><input name="newPassword" type="password" minLength={8} autoComplete="new-password" className={field} /></Field></section><aside className="rounded-[2rem] border border-border/60 bg-card/75 p-5 shadow-lg sm:p-6"><div className="flex items-center gap-3"><ShieldAlert className="size-5 text-amber-500" /><h2 className="font-black">Account state</h2></div><Field label="Access"><select name="accountState" defaultValue={user.accountState} className={field}><option value="ACTIVE">Active</option><option value="LOCKED">Locked</option><option value="BANNED">Banned</option></select></Field><Field label="Lock duration in hours"><input name="lockHours" type="number" min="0" placeholder="0 = indefinite" className={field} /></Field><Field label="Reason"><textarea name="restrictionReason" rows={4} defaultValue={user.restrictionReason ?? ''} className={`${field} h-auto py-3`} /></Field><button className="mt-5 inline-flex h-11 w-full items-center justify-center gap-2 rounded-full bg-foreground text-xs font-bold text-background"><Save className="size-4" /> Apply secured changes</button></aside></form></div></main>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="mt-4 block"><span className="mb-2 block text-[10px] font-bold uppercase tracking-[.14em] text-muted-foreground">{label}</span>{children}</label>; }
